services:
    behappy_invoice_plugin.event.listener.order:
        class: BeHappy\SyliusInvoicePlugin\Event\Listener\OrderListener
        public: true
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@behappy_invoice_plugin.custom_factory.invoice'
            - '@event_dispatcher'

    behappy_invoice_plugin.event.listener.admin.order.show.after_shipment:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@BeHappySyliusInvoicePlugin/Invoice/Admin/block.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.order.show.after_shipments, method: onBlockEvent }

    behappy_invoice_plugin.event.listener.shop.order.show.after_content_header:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@BeHappySyliusInvoicePlugin/Invoice/Shop/view_invoice_button.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.account.order.show.after_content_header, method: onBlockEvent }

    behappy_invoice_plugin.admin.invoice_menu_builder_listener:
        class: BeHappy\SyliusInvoicePlugin\Event\Listener\InvoiceMenuBuilderListener
        tags:
            - { name: kernel.event_listener, event: sylius.menu.admin.main, method: addInvoiceItem }
