behappy_invoice_plugin.admin.view_pdf:
    path: '/orders/{id}/invoices/{invoiceId}/pdf'
    methods: [ GET ]
    requirements:
        id: '\d+'
        invoiceId: '\d+'
    defaults:
        _controller: BeHappySyliusInvoicePlugin:Admin\Invoice:viewPdf

behappy_invoice_plugin:
    resource: |
        alias: behappy_invoice_plugin.invoice
        section: admin
        templates: SyliusAdminBundle:Crud
        only: ['index']
        grid: behappy_invoice_plugin_invoice
        permission: true
        vars:
            all:
                subheader: behappy_invoice_plugin.ui.invoices
            index:
                icon: file pdf
    type: sylius.resource

behappy_invoice_plugin_admin_invoice_show:
    path: /invoices/{id}
    methods: [GET]
    defaults:
        _controller: BeHappySyliusInvoicePlugin:Admin\Invoice:read
        _sylius:
            section: admin
            permission: true
