imports:
    - { resource: '@BeHappySyliusInvoicePlugin/Resources/config/resources/invoice.yml' }
    - { resource: '@BeHappySyliusInvoicePlugin/Resources/config/resources/invoice_company_data.yml' }
