winzou_state_machine:
    sylius_order_payment:
        callbacks:
            after:
                sylius_order_paid:
                    on: [ 'pay' ]
                    do: [ '@behappy_invoice_plugin.event.listener.order', 'onOrderPaid' ]
                    args: [ 'object' ]