services:
    bhc_invoice.listener.admin.order.show.after_shipment:
        class: Sylius\Bundle\UiBundle\Block\BlockEventListener
        arguments:
            - '@@BHCInvoice/Invoice/block.html.twig'
        tags:
            - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.order.show.after_shipments, method: onBlockEvent }