behappy_show_invoice_shop_pdf:
    path: '/orders/{number}/invoice-pdf'
    methods: [ 'GET' ]
    defaults:
        _controller: BehappyInvoicePlugin:Invoice:renderPdf

behappy_show_invoice_shop:
    path: '/orders/{number}/invoice'
    methods: [ 'GET' ]
    defaults:
        _controller: BehappyInvoicePlugin:Invoice:render