behappy_show_invoice_admin_pdf:
    path: '/orders/{id}/invoice-pdf'
    methods: [ 'GET' ]
    requirements:
        id: '\d+'
    defaults:
        _controller: BehappyInvoicePlugin:Invoice:renderPdf

behappy_show_invoice_admin:
    path: '/orders/{id}/invoice'
    methods: [ 'GET' ]
    requirements:
        id: '\d+'
    defaults:
        _controller: BehappyInvoicePlugin:Invoice:render