BeHappy\SyliusInvoicePlugin\Entity\Order:
    type: mappedSuperclass
    table: sylius_order
    oneToMany:
        invoices:
            targetEntity: BeHappy\SyliusInvoicePlugin\Entity\InvoiceInterface
            mappedBy: order
